import boto3
import os
from dotenv import load_dotenv

load_dotenv()

class AWSHandler:

    def __init__(self):
        self.region = os.getenv('AWS_REGION', 'ap-south-1')
        self.s3_bucket = os.getenv('S3_BUCKET_NAME', 'ai-qa-demo-reports-sabyag42')
        self.sns_topic_arn = os.getenv('SNS_TOPIC_ARN')

        self.s3 = boto3.client('s3', region_name=self.region)
        self.sns = boto3.client('sns', region_name=self.region)

    def upload_report(self, filepath: str, issue_key: str) -> str:
        filename = os.path.basename(filepath)
        s3_key = f"reports/{issue_key}/{filename}"

        print(f"Uploading report to S3: {s3_key}")

        self.s3.upload_file(
            filepath,
            self.s3_bucket,
            s3_key,
            ExtraArgs={'ContentType': 'text/html'}
        )

        # Generate presigned URL valid for 7 days
        url = self.s3.generate_presigned_url(
            'get_object',
            Params={
                'Bucket': self.s3_bucket,
                'Key': s3_key
            },
            ExpiresIn=604800
        )

        print(f"Report URL: {url}")
        return url

    def send_notification(self, issue_key: str, 
                         status: str, report_url: str) -> None:
        if not self.sns_topic_arn:
            print("SNS_TOPIC_ARN not set — skipping notification")
            return

        emoji = "✅" if status == "PASSED" else "❌"
        subject = f"{emoji} AI QA Pipeline — {issue_key} {status}"

        message = f"""
AI QA Automation Pipeline Results
==================================
Issue:    {issue_key}
Status:   {status}
Report:   {report_url}

Pipeline Steps:
1. Jira story fetched
2. Test cases generated by GPT-4o
3. Playwright script generated by GPT-4o
4. Tests executed automatically
5. Report uploaded to S3

View full report: {report_url}
"""

        self.sns.publish(
            TopicArn=self.sns_topic_arn,
            Subject=subject,
            Message=message
        )

        print(f"Notification sent to SNS topic")


if __name__ == "__main__":
    handler = AWSHandler()

    # Test S3 upload with dummy file
    with open("reports/test.html", "w") as f:
        f.write("<h1>Test Report</h1>")

    url = handler.upload_report("reports/test.html", "SCRUM-5")
    print(f"Uploaded: {url}")