import os
from datetime import datetime


class ReportGenerator:

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate(self, story: dict, test_cases: str, 
                 script: str, test_result: dict) -> str:

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        status = "PASSED" if test_result['passed'] else "FAILED"
        status_color = "#2ecc71" if test_result['passed'] else "#e74c3c"

        # Format test cases for HTML
        test_cases_html = test_cases.replace('\n', '<br>')

        # Format script for HTML
        script_clean = script.replace(
            "```python", "").replace("```", "").strip()

        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI QA Report — {story['key']}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', sans-serif;
            background: #0f1117;
            color: #e0e0e0;
            padding: 40px;
        }}
        .header {{
            background: linear-gradient(135deg, #1a1a2e, #16213e);
            border: 1px solid #0f3460;
            border-radius: 12px;
            padding: 30px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            font-size: 28px;
            color: #00d4ff;
            margin-bottom: 8px;
        }}
        .header p {{
            color: #888;
            font-size: 14px;
        }}
        .status-badge {{
            display: inline-block;
            background: {status_color};
            color: white;
            padding: 8px 20px;
            border-radius: 20px;
            font-weight: bold;
            font-size: 16px;
            margin-top: 15px;
        }}
        .card {{
            background: #1a1a2e;
            border: 1px solid #0f3460;
            border-radius: 12px;
            padding: 25px;
            margin-bottom: 25px;
        }}
        .card h2 {{
            color: #00d4ff;
            font-size: 18px;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 1px solid #0f3460;
        }}
        .story-summary {{
            font-size: 18px;
            color: #fff;
            margin-bottom: 10px;
        }}
        .story-key {{
            background: #0f3460;
            color: #00d4ff;
            padding: 4px 10px;
            border-radius: 4px;
            font-size: 13px;
            margin-right: 10px;
        }}
        .test-cases {{
            background: #0f1117;
            border-radius: 8px;
            padding: 20px;
            font-size: 14px;
            line-height: 1.8;
            color: #ccc;
        }}
        pre {{
            background: #0f1117;
            border-radius: 8px;
            padding: 20px;
            font-size: 13px;
            overflow-x: auto;
            color: #a8ff78;
            line-height: 1.6;
        }}
        .meta {{
            display: flex;
            gap: 20px;
            flex-wrap: wrap;
        }}
        .meta-item {{
            background: #0f3460;
            padding: 10px 16px;
            border-radius: 8px;
            font-size: 13px;
        }}
        .meta-item span {{
            color: #00d4ff;
            font-weight: bold;
        }}
        .footer {{
            text-align: center;
            color: #444;
            font-size: 13px;
            margin-top: 40px;
        }}
    </style>
</head>
<body>

    <div class="header">
        <h1>AI QA Automation Report</h1>
        <p>Generated by GPT-4o · Executed by Playwright · {timestamp}</p>
        <div class="status-badge">{status}</div>
    </div>

    <div class="card">
        <h2>Jira Story</h2>
        <div class="story-summary">
            <span class="story-key">{story['key']}</span>
            {story['summary']}
        </div>
        <p style="color:#888; font-size:14px; margin-top:10px;">
            {story['description']}
        </p>
    </div>

    <div class="card">
        <h2>Test Execution Summary</h2>
        <div class="meta">
            <div class="meta-item">Status: <span>{status}</span></div>
            <div class="meta-item">Story: <span>{story['key']}</span></div>
            <div class="meta-item">Generated by: <span>GPT-4o</span></div>
            <div class="meta-item">Executed by: <span>Playwright</span></div>
            <div class="meta-item">Timestamp: <span>{timestamp}</span></div>
        </div>
    </div>

    <div class="card">
        <h2>AI Generated Test Cases</h2>
        <div class="test-cases">{test_cases_html}</div>
    </div>

    <div class="card">
        <h2>AI Generated Playwright Script</h2>
        <pre>{script_clean}</pre>
    </div>

    <div class="footer">
        AI QA Demo · Built with OpenAI GPT-4o + Playwright + Python
    </div>

</body>
</html>
"""

        filepath = os.path.join(
            self.output_dir, f"report_{story['key']}.html")
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"Report saved to: {filepath}")
        return filepath


if __name__ == "__main__":
    # Quick test with dummy data
    story = {
        'key': 'SCRUM-5',
        'summary': 'User can login with valid credentials',
        'description': 'As a user I want to login...'
    }
    test_cases = "TC1: Valid login\nTC2: Invalid login"
    script = "def test_login(): pass"
    result = {'passed': True}

    generator = ReportGenerator()
    filepath = generator.generate(story, test_cases, script, result)
    print(f"Open: {filepath}")